user:
  insert-user: "INSERT INTO users (email, login, name, birthday)
                VALUES (?, ?, ?, ?)"
  select-users: "SELECT * FROM users"
  select-by-id: "SELECT * FROM users WHERE id = ?"
  delete: "DELETE FROM users WHERE id = ?"
  update-user: "UPDATE users SET email = ?, name = ?, login = ?, birthday = ?
               WHERE id = ?"
  friends-by-user-id: "SELECT * FROM users 
                      WHERE id IN (
                      SELECT friend_id FROM friends WHERE user_id = ?)"
  insert-friend: "INSERT INTO friends (user_id, friend_id) VALUES (?, ?)"
  remove-friend: "DELETE FROM friends WHERE user_id = ? AND friend_id = ?"
  select-mutual-friends: "SELECT u1.id, u1.email, u1.login, u1.name, u1.birthday
                        FROM users u1
                        JOIN friends f1 ON f1.friend_id = u1.id
                        JOIN friends f2 ON f2.friend_id = f1.friend_id AND f2.user_id = ?
                        WHERE f1.user_id = ?"