server:
  port: 8080

spring:
  config:
    import:
      - classpath:application-film.yml
      - classpath:application-user.yml
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    locations: classpath:db/migration